# Generated by Django 4.1.5 on 2023-01-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic_url',
            field=models.URLField(blank=True, db_column='pic_url', max_length=512, null=True),
        ),
    ]
