# Generated by Django 4.1.5 on 2023-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_remove_movie_movie_name_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(db_column='description', default=1),
            preserve_default=False,
        ),
    ]
