# Generated by Django 4.1.5 on 2023-01-31 13:09
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0008_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(auto_now_add=True, db_column='rating_date', default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
